# Generated by Django 5.2 on 2025-07-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TumorPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('uploaded_mri', models.ImageField(upload_to='uploads/mri/')),
                ('uploaded_pet', models.ImageField(upload_to='uploads/pet/')),
                ('fused_image', models.ImageField(blank=True, null=True, upload_to='uploads/fused/')),
                ('prediction_result', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
